version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

deploy-job:
 docker:
   - image: my-image-version-tag
 working_directory: /tmp/my-project
 steps:
   - run:
       name: Deploy Master to Firebase
       command: ./node_modules/.bin/firebase deploy --token="1/OV5xGfb_5CqiCKIhxLgJH0A3U6t-Ju0rjxeOmSW4igA"

workflows:
version: 2

-deploy:
  jobs:
    - build-job
    - deploy-job:
        requires:
          - build-job
        filters:
          branches:
            only: master
